### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by jdx** [jdx/demand#21]
I feel like we should publish a "1.0" revision once we hit feature parity with huh—which I think we're close to. I think it would be also good to create a CHANGELOG at that point. cc @roele

**Comment by jdx** [comment]
@roele what are your thoughts on this?

**Comment by roele** [comment]
Agree on that. Ideally the changelog is auto-generated (via `git-cliff`?) something i can have a look at...

Question is, what features we want to have in a version 1.0. The usability of the open topics like `form`, `text` is questionable for a 1.0 version. 

Also what else do we need in terms of automation, documentation and CI?
Guess will need to read up on documentation of APIs, deployment of crates etc.

**Comment by jdx** [comment]
> Ideally the changelog is auto-generated (via git-cliff?) something i can have a look at

Up to you, I'm fine manual or whatever tool you want to try

> The usability of the open topics like form, text is questionable for a 1.0 version.

I think we can skip these

> Also what else do we need in terms of automation, documentation and CI?

I think we're good enough for 1.0 now with what is in github actions

The docs get built [here](https://docs.rs/demand) when the crate is published. We can probably go through that and improve it in places but it looks alright to me for a 1.0.

**Comment by jdx** [comment]
I think it all looks great @roele, should we ship 1.0? I went ahead and added you to the crate if you want to do it, otherwise I'm happy to.

Also, I like to use [`cargo-release`](https://github.com/crate-ci/cargo-release) which looks like it has some changelog integration. At minimum we can add a pre-release hook to generate the changelog I think.

**Comment by roele** [comment]
Thanks! Go ahead with the release, will not get to it the next few hours.
Will make myself familiar with `cargo-release` tomorrow, the less dependencies on other tools for the changelog the better.

**Comment by jdx** [comment]
it was pretty easy actually: https://github.com/jdx/demand/commit/dc60fa6bd3b18df9692cd23194be48d9150db667

if you ever do a release, just run `mise run release -x major|minor|patch`. You may need to setup gpg/ssh commit signing if you haven't already.
