### ISSUE TITLE
remove leading space from rendered output

### ISSUE THREAD

**Issue by roele** [jdx/demand#55]
Currently components print their result with a leading space in front of every line.

<img width="543" alt="Screenshot 2024-05-15 at 15 02 37" src="https://github.com/jdx/demand/assets/181773/9f779e7f-09e2-426d-830e-206ced20b21d">

Apart from not providing much visual value it also complicates code a bit since that space needs to be accounted for on every new line that is rendered.

IMO this leading space should be removed.

**Comment by yk-amarly-20** [comment]
Hello, @roele @jdx !
May I work on this issue?

I tried running the example, and I understand that this issue has not yet been resolved.

I understand that fixing around this area and the tests, for example, the Confirm struct, would address this.
https://github.com/jdx/demand/blob/9542af2b7888609cb6f6678a439dc7f6d0ac9306/src/confirm.rs#L139

**Comment by roele** [comment]
Hi @yk-amarly-20
Help around this would be much appreciated since i currently don't have much time on my hands.

The issue affects pretty much all input types of which `Input` might be a bit more involved with the cursor handling. 

For example:
https://github.com/jdx/demand/blob/9542af2b7888609cb6f6678a439dc7f6d0ac9306/src/input.rs#L447

If you have any questions don't hesitate to reach out.
