### ISSUE TITLE
[security] password input renders password on success

### ISSUE THREAD

**Issue by rendarz** [jdx/demand#59]
Consider this very simple code:
```rust
let input = demand::Input::new("Password:")
  .inline(true)
  .prompt("")
  .password(true);
let name = input.run().expect("error running input");
```

It lets me to input a password, and the password characters are indeed hidden by `*` characters.
But when I press enter, the password is written in stdout IN CLEAR, like if its a normal input entry.
Why? Am I missing something, or doing something wrong?
IMHO, the flag `.password(true)` should absolutely block this,  or it could generate UNWANTED SURPRISES!
NOTE: It works like that even with `.inline(false)`.

![2](https://github.com/jdx/demand/assets/12814431/d46bc26e-4797-4ec5-9751-4b5cfc63effb)
![1](https://github.com/jdx/demand/assets/12814431/60419c0b-b5d9-4328-8130-7c0bfcae9f7d)

**Comment by roele** [comment]
@rendarz Indeed a valid concern! Thanks for reporting this.
