### ISSUE TITLE
Quit interactive menus with single-key shortcuts: escape, q, c

### ISSUE THREAD

**Issue by eugenesvk** [jdx/demand#62]
Currently accepted navigation keys are: ↑/↓/k/j up/down • / filter • enter confirm

But Escape is also very common to cancel various UI operations. Or maybe you could also have `q` and `c` for quitting/cancelling, which would be even more convenient

**Comment by roele** [comment]
Agreed that escape should be supported. For `q` and `c` i see conflicts with some of the inputs that automatically map characters like the Dialog.

**Comment by eugenesvk** [comment]
Does `z` also conflict?

**Comment by roele** [comment]
Potentially yes. For Confirm/Dialog the mapping is dynamic and depends on the option labels. If you have a Dialog with options "Yes" / "No" / "Cancel", first character of each option is mapped (y/n/c in this case) to a key for selecting the value.

**Comment by jdx** [comment]
I think `q` is the only one that makes sense. `c` for cancel seems very non-standard.

**Comment by eugenesvk** [comment]
But are the option labels user-configurable? Also that dynamic mapping can have its alphabet reduced by one letter if it's defined to be used for exit
