### ISSUE TITLE
Automatically use fuzzy find

### ISSUE THREAD

**Issue by hverlin** [jdx/demand#63]
There is a way to filter a list currently with `demand`. 

However, I think it would be nice if there was the option to make it work like `fzf` where you are immediately in filter mode. 

This would allow `mise run` for example to work more like:
```shell
mise run $(mise tasks | fzf | awk '{print $1}')
```
If this option is set, the `vim` shortcuts will need to be disabled. It would also be incompatible with https://github.com/jdx/demand/issues/62, leaving `ctrl+c` as the only way to interrupt the selection

**Comment by jdx** [comment]
we don't actually have fuzzy finding, it's just a simple string match I think. So we'd need to also add fuzzy-finding.

e.g.: if you have a task named "docker:cargo" you should be able to find it with "dc". That works in fzf, not so in demand.

**Comment by jdx** [comment]
I personally like this idea, maybe behind a setting, but notably it would mean we could not do this: https://github.com/jdx/demand/issues/62

**Comment by roele** [comment]
For #62 i think mapping characters like `c` or `q` might conflict with the auto-mapping we currently have for the Confirm/Dialog which maps the first character of the available actions for input selection.

**Comment by eugenesvk** [comment]
Another alternative, which for shorter lists is even better than the awesomeness of fuzzy finding is allowing "accelerator keys", then you could have the fastest way to pick a task - with just a single key

so pressing <kbd>b</kbd> or <kbd>c</kbd> or <kbd>d</kbd> etc. would pick the task - no need to up/down, no need to press Enter. (you could even have a config to preserve j/k by making these unusable for accelerator to have the best of each approach)
(and the keys should be added in an extra column and highlighted visually)
- <kbd>b</kbd> build
- <kbd>c</kbd> check
- <kbd>d</kbd> doc


<img width="373" alt="mise_1k" src="https://github.com/user-attachments/assets/70128f37-a186-4f22-b21a-32296e4b20e6">


(And this will even save you one key even if you used 1-key aliases by not requiring a space separator :))

**Comment by jdx** [comment]
> For #62 i think mapping characters like `c` or `q` might conflict with the auto-mapping we currently have for the Confirm/Dialog which maps the first character of the available actions for input selection.

my thought was that we could just add an optional setting for `self.filtering` like this:

```rs
use demand::{DemandOption, Select};

fn main() {
    let ms = Select::new("Toppings")
        .description("Select your topping")
        .filterable(true)
        .filtering(true)
        .option(DemandOption::new("Lettuce"))
        .option(DemandOption::new("Tomatoes"))
        .option(DemandOption::new("Charm Sauce"))
        .option(DemandOption::new("Jalapenos").label("Jalapeños"))
        .option(DemandOption::new("Cheese"))
        .option(DemandOption::new("Vegan Cheese"))
        .option(DemandOption::new("Nutella"));
    ms.run().expect("error running select");
}
```

that would just set `self.filtering` to true so you're already in that state when you drop in:

https://github.com/jdx/demand/blob/1d14dec9731df3efe594f236edfd410a150d9d39/src/multiselect.rs#L140

it'd be a little weird since you could exit out of it, but that's probably fine

**Comment by jdx** [comment]
I wonder if we could just drop this in: https://github.com/skim-rs/fuzzy-matcher
