### ISSUE TITLE
descriptions on select/multiselect

### ISSUE THREAD

**Issue by jdx** [jdx/demand#65]
I'd like to be able to add a description to DemandOption that is distinct in the UI from the label:

something like this, probably with the description dimmed
```
mise  test ❯ mise run
Tasks
Select a tasks to run
> clean           my description
↑/↓/k/j up/down • / filter • enter confirm
```

**Comment by stevelandeyasana** [comment]
This is pretty good, but there might still be room to improve the UX. My own ideal would be to say `mise run` and then just start typing to fuzzy find, with descriptions printed alongside task names, and hit Enter to run. Still happy to see this though!
